<a href="https://colab.research.google.com/github/aleakucing/Pembelajaran-Memsin/blob/main/JS05/JS05_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [16]:
#1 : load data
import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/PemMes/JS5/spam.csv', encoding='latin-1')
df = df.rename(columns={'v1': 'Labels', 'v2': 'SMS'})

df.head()

,Labels,SMS,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [10]:
#2.a drop column
df = df.drop(df.iloc[:,2:], axis=1)

df.head()

     v1                                                 v2
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [15]:
#2.b inspeksi data
print(df['Labels'].value_counts())
print('\n' + '='*40 + '\n')

print(df.info())
print('\n' + '='*40 + '\n')

print(df.describe())

Labels
ham     4825
spam     747
Name: count, dtype: int64

========================================

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Labels      5572 non-null   object
 1   SMS         5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB
None

========================================

       Labels                     SMS  \
count    5572                    5572
unique      2                    5169
top       ham  Sorry, I'll call later
freq     4825                      30

                                               Unnamed: 2  \
count                                                  50
unique                                                 43
top      bt not his girlfrnd... G o o d n i g h t . . .@"
freq                                                    3

                   Unnamed: 3 Unnamed: 4
count                      12          6
unique                     10          5
top      MK17 92H. 450Ppw 16"    GNT:-)"
freq                        2          2

In [17]:
#2.c encoding label
new_labels = {
    'spam': 1,
    'ham': 0
}

df['Labels'] = df['Labels'].map(new_labels)

df.head()

,Labels,SMS,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,0,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,0,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,0,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,0,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [18]:
#2.d training dan evaluasi model
X = df['SMS'].values
y = df['Labels'].values

In [20]:
#3. ektraksi fitur
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)
bow = CountVectorizer()

X_train = bow.fit_transform(X_train)
X_test = bow.transform(X_test)

In [23]:
#4. training dan evaluasi model
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

mnb = MultinomialNB()

mnb.fit(X_train, y_train)

y_pred_train = mnb.predict(X_train)

acc_train = accuracy_score(y_train, y_pred_train)

y_pred_test = mnb.predict(X_test)

acc_test = accuracy_score(y_test, y_pred_test)

print(f'Hasil akurasi data train: {acc_train}')
print(f'Hasil akurasi data test: {acc_test}')

Hasil akurasi data train: 0.9946152120260264
Hasil akurasi data test: 0.9775784753363229